name       : sequeler
version    : 0.5.6
release    : 3
source     :
    - https://github.com/Alecaddd/sequeler/archive/v0.5.6.tar.gz : 478416295db509a484feac795a9150688c6bcdd4cca959439ace100b4ab71a64
license    : GPL-3.0-only
component  : database
summary    : Sequeler is a native Linux SQL client built in Vala and Gtk.
description: |
    Sequeler is a native Linux SQL client built in Vala and Gtk. It allows you to connect to your local and remote databases, write SQL in a handy text editor with language recognition, and visualize SELECT results in a Gtk.Grid Widget.
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(granite)
    - pkgconfig(gtksourceview-3.0)
    - pkgconfig(libgda-5.0)
    - pkgconfig(libsecret-1)
    - vala
# gnome-keyring is required at least until kwallet can handle libsecret (T5690)
rundeps    :
    - gnome-keyring
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
