name       : sequeler
version    : 0.8.2
website    : https://github.com/Alecaddd/sequeler
release    : 13
source     :
    - https://github.com/Alecaddd/sequeler/archive/v0.8.2.tar.gz : 66ae40d8fc6bf5aa0f5608ffc32c3b66c2ff78deb675d301112a8eca7f050876
license    : GPL-3.0-only
component  : database
summary    : Sequeler is a native Linux SQL client built in Vala and Gtk
description: |
    Sequeler is a native Linux SQL client built in Vala and Gtk. It allows you to connect to your local and remote databases, write SQL in a handy text editor with language recognition, and visualize SELECT results in a Gtk.Grid Widget.
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(granite)
    - pkgconfig(gtksourceview-3.0)
    - pkgconfig(libgda-5.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(libssh2)
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
