name       : sequeler
version    : 0.8.0
website    : https://github.com/Alecaddd/sequeler
release    : 10
source     :
    - https://github.com/Alecaddd/sequeler/archive/v0.8.0.tar.gz : 471fdf63fda568d4caddf6182897518e4b7abc1b4f5dfb466bd1dfc86d380f0c
license    : GPL-3.0-only
component  : database
summary    : Sequeler is a native Linux SQL client built in Vala and Gtk.
description: |
    Sequeler is a native Linux SQL client built in Vala and Gtk. It allows you to connect to your local and remote databases, write SQL in a handy text editor with language recognition, and visualize SELECT results in a Gtk.Grid Widget.
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(granite)
    - pkgconfig(gtksourceview-3.0)
    - pkgconfig(libgda-5.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(libssh2)
    - vala
# gnome-keyring is required at least until kwallet can handle libsecret (T5690)
rundeps    :
    - gnome-keyring
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
